#!/usr/bin/env bash
python pre_treatment/script/extract_character_speech.py tei-lustig am-letzte-maskebal.xml
python pre_treatment/script/extract_character_speech.py tei-lustig babette-mach-s-fenster-zue.xml
python pre_treatment/script/extract_character_speech.py tei-lustig bi-de-wilde.xml
python pre_treatment/script/extract_character_speech.py tei-lustig d-gsellschaftere.xml
python pre_treatment/script/extract_character_speech.py tei-lustig d-huslit-vo-dr-frau-suppedunke.xml
python pre_treatment/script/extract_character_speech.py tei-lustig d-milhuser-in-paris.xml
python pre_treatment/script/extract_character_speech.py tei-lustig d-singstund.xml
python pre_treatment/script/extract_character_speech.py tei-lustig d-tante-domino.xml
python pre_treatment/script/extract_character_speech.py tei-lustig dr-astronom.xml
python pre_treatment/script/extract_character_speech.py tei-lustig dr-chineserfranz.xml
python pre_treatment/script/extract_character_speech.py tei-lustig dr-fechtmeister.xml
python pre_treatment/script/extract_character_speech.py tei-lustig dr-hochzitstag.xml
python pre_treatment/script/extract_character_speech.py tei-lustig drei-schwarze-liebschafte.xml
python pre_treatment/script/extract_character_speech.py tei-lustig drizehne.xml
python pre_treatment/script/extract_character_speech.py tei-lustig hans-dich-hats.xml
python pre_treatment/script/extract_character_speech.py tei-lustig im-gretele-sine-kunstler.xml
python pre_treatment/script/extract_character_speech.py tei-lustig im-julie-si-gheimniss.xml
python pre_treatment/script/extract_character_speech.py tei-lustig in-dr-falle.xml
python pre_treatment/script/extract_character_speech.py tei-lustig milhuser-bilder.xml
python pre_treatment/script/extract_character_speech.py tei-lustig ne-hiroth-dur-d-extrapost.xml
python pre_treatment/script/extract_character_speech.py tei-lustig ne-jumpfre-wo-nitt-hirothe-will.xml
python pre_treatment/script/extract_character_speech.py tei-lustig ne-scandal.xml
python pre_treatment/script/extract_character_speech.py tei-lustig uf-bsuech-bi-dr-frau.xml
python pre_treatment/script/extract_character_speech.py tei-lustig vor-un-no-dr-hochzit.xml
python pre_treatment/script/extract_character_speech.py tei-lustig z-nacht-am-zehne.xml
python pre_treatment/script/extract_character_speech.py tei-lustig zwei-erfindunge.xml
python pre_treatment/script/extract_character_speech.py tei arnold-der-pfingstmontag.xml
python pre_treatment/script/extract_character_speech.py tei bastian-dr-hans-im-schnokeloch.xml
python pre_treatment/script/extract_character_speech.py tei bastian-dr-maischter-hett-gewunne.xml
python pre_treatment/script/extract_character_speech.py tei bastian-e-sportschochzitt.xml
python pre_treatment/script/extract_character_speech.py tei bastian-hofnarr-heidideldum.xml
python pre_treatment/script/extract_character_speech.py tei clemens-a-latzi-visit.xml
python pre_treatment/script/extract_character_speech.py tei clemens-charlot.xml
python pre_treatment/script/extract_character_speech.py tei clemens-chrischtowe.xml
python pre_treatment/script/extract_character_speech.py tei clemens-gift.xml
python pre_treatment/script/extract_character_speech.py tei greber-d-jumpfer-prinzesse.xml
python pre_treatment/script/extract_character_speech.py tei greber-lucie.xml
python pre_treatment/script/extract_character_speech.py tei greber-sainte-cecile.xml
python pre_treatment/script/extract_character_speech.py tei hart-dr-poetisch-oscar.xml
python pre_treatment/script/extract_character_speech.py tei horsch-d-madam-fahrt-velo.xml
python pre_treatment/script/extract_character_speech.py tei jost-daa-im-narrehuss.xml
python pre_treatment/script/extract_character_speech.py tei jost-so-e-liederlicher-frack.xml
python pre_treatment/script/extract_character_speech.py tei kettner-uff-dr-hochzittsreis.xml
python pre_treatment/script/extract_character_speech.py tei kuehne-bureaukrate.xml
python pre_treatment/script/extract_character_speech.py tei riff-s-paradies.xml
python pre_treatment/script/extract_character_speech.py tei riff-sainte-barbe.xml
python pre_treatment/script/extract_character_speech.py tei schneegans-steckelburjer-universite-saaue.xml
python pre_treatment/script/extract_character_speech.py tei stoskopf-dr-herr-maire.xml
python pre_treatment/script/extract_character_speech.py tei stoskopf-dr-hoflieferant.xml
python pre_treatment/script/extract_character_speech.py tei stoskopf-ins-ropfers-apothek.xml
python pre_treatment/script/extract_character_speech.py tei weber-yo-yo.xml
python pre_treatment/script/extract_character_speech.py tei2 bastian-s-gaischtert-im-huss.xml
python pre_treatment/script/extract_character_speech.py tei2 bastian-struwelpeter.xml
python pre_treatment/script/extract_character_speech.py tei2 clemens-d-brueder.xml
python pre_treatment/script/extract_character_speech.py tei2 clemens-dr-amerikaner.xml
python pre_treatment/script/extract_character_speech.py tei2 fuchs-heimlichi-lieb.xml
python pre_treatment/script/extract_character_speech.py tei2 greber-s-teschtament.xml
python pre_treatment/script/extract_character_speech.py tei2 gunther-dr-cousin-refractaire.xml
python pre_treatment/script/extract_character_speech.py tei2 hahn-jungi-madamme.xml
python pre_treatment/script/extract_character_speech.py tei2 horsch-neui-hosse.xml
python pre_treatment/script/extract_character_speech.py tei2 huck-a-gelungener-patient.xml
python pre_treatment/script/extract_character_speech.py tei2 jost-d-satisfaction.xml
python pre_treatment/script/extract_character_speech.py tei2 jost-dr-erscht-handel.xml
python pre_treatment/script/extract_character_speech.py tei2 jost-e-dienschtbott-wurd-gsuecht.xml
python pre_treatment/script/extract_character_speech.py tei2 kleisecker-dr-schnider-von-gambse.xml
python pre_treatment/script/extract_character_speech.py tei2 lasch-dr-babbler.xml
python pre_treatment/script/extract_character_speech.py tei2 riff-d-schloofere.xml
python pre_treatment/script/extract_character_speech.py tei2 riff-dr-hasestrickler.xml
python pre_treatment/script/extract_character_speech.py tei2 sengelin-d-mamsell-elis.xml
python pre_treatment/script/extract_character_speech.py tei2 stoskopf-e-diplomat.xml
python pre_treatment/script/extract_character_speech.py tei2 stoskopf-e-mordsaffar.xml
python pre_treatment/script/extract_character_speech.py tei2 stoskopf-wenn-d-fraue-wahle.xml
python pre_treatment/script/extract_character_speech.py tei2 wagner-die-greifensteiner.xml
python pre_treatment/script/extract_character_speech.py tei2 weber-am-wihnachtsowe-bym-e-kriejsblinde.xml
python pre_treatment/script/extract_character_speech.py tei2 weber-e-bissel-lieb.xml
python pre_treatment/script/extract_character_speech.py tei2 weber-wihnachtsstimme.xml
python pre_treatment/script/extract_character_speech.py tei2 weigel-in-dr-awril-gschickt.xml